---
- name: Prepare the application
  hosts: localhost
  tasks:
    - name: Pack the repository
      shell:
        cmd: git archive -o ansible/app.tar.gz --prefix=app/ --add-file=owm-appid.txt main
        chdir: ..
- name: Upload the project
  become: true
  hosts: prod
  tasks:
    - name: Upload
      copy:
        src: app.tar.gz
        dest: /home/app/
    - name: Remove previous version
      command:
        cmd: rm -rf app
        chdir: /home/app/
    - name: Unpack
      command: 
        cmd: tar xzf app.tar.gz
        chdir: /home/app/
    - name: Clean up
      command:
        cmd: rm app.tar.gz
        chdir: /home/app/
    - name: Change ownership
      command:
        cmd: "chown -R app: /home/app/app"
- name: Set up firewall
  hosts: prod
  become: true
  tasks:
    - name: Install ufw
      apt:
        state: latest
        pkg:
        - ufw
    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH
    - name: Allow HTTP
      ufw:
        rule: allow
        port: '80'
        proto: tcp
    - name: Allow HTTPS
      ufw:
        rule: allow
        port: '443'
        proto: tcp
    - name: Enable ufw
      ufw:
        state: enabled
        policy: reject
- name: Prepare the environment
  hosts: prod
  become: true
  tasks:
    - name: Install necessary packages
      apt:
        state: latest
        pkg:
        - debian-keyring
        - debian-archive-keyring
        - apt-transport-https
        - pgp
        - acl
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Install Docker
      apt:
        state: latest
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: Add Caddy GPG key
      apt_key:
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        state: present
    - name: Add Caddy Apt repository
      apt_repository:
        repo: deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
        state: present
    - name: Install Caddy
      apt:
        state: latest
        pkg:
        - caddy
- name: Prepare the containers
  hosts: prod
  tasks:
    - name: Reclaim disk space
      command: docker system prune -f
    - name: Build the images
      become: true
      become_user: app
      command:
        cmd: docker compose -f compose.prod.yaml build --no-cache
        chdir: /home/app/app
- name: Run the app
  hosts: prod
  become: true
  tasks:
    - name: Install the service
      copy:
        src: weatherapp.service
        dest: /etc/systemd/system
    - name: Run the service
      systemd_service:
        name: weatherapp
        state: restarted
        daemon_reload: true
        enabled: true
